//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soapService.RedPillReference {
    using System.Runtime.Serialization;
    using System;
    using System.ServiceModel;
    using soapService.ActualRedPill;
    
    
    
    
  
    
   // [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
   //   [System.ServiceModel.ServiceContractAttribute(Namespace="http://KnockKnock.readify.net")]
   // [ServiceContract(Namespace = @"http://aspspider.ws/hemantham")]
    [ServiceContract(Namespace = "http://KnockKnock.readify.net")]
    public interface IRedPill {

        [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/WhoAreYou", ReplyAction = "http://KnockKnock.readify.net/IRedPill/WhoAreYouResponse")]
        ContactDetails WhoAreYou();
        
        [System.ServiceModel.OperationContract(Action="http://KnockKnock.readify.net/IRedPill/FibonacciNumber", ReplyAction="http://KnockKnock.readify.net/IRedPill/FibonacciNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException), Action="http://KnockKnock.readify.net/IRedPill/FibonacciNumberArgumentOutOfRangeException" 
            , Name="ArgumentOutOfRangeException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        long FibonacciNumber(long n);
        
        [System.ServiceModel.OperationContract(Action="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", ReplyAction="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThisResponse")]
        TriangleType WhatShapeIsThis(int a, int b, int c);
        
        [System.ServiceModel.OperationContract(Action="http://KnockKnock.readify.net/IRedPill/ReverseWords", ReplyAction="http://KnockKnock.readify.net/IRedPill/ReverseWordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://KnockKnock.readify.net/IRedPill/ReverseWordsArgumentNullException", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        string ReverseWords(string s);
    }
    
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //public interface IRedPillChannel : soapService.RedPillReference.IRedPill, System.ServiceModel.IClientChannel {
    //}
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    //public partial class RedPillClient : System.ServiceModel.ClientBase<soapService.RedPillReference.IRedPill>, soapService.RedPillReference.IRedPill {
        
    //    public RedPillClient() {
    //    }
        
    //    public RedPillClient(string endpointConfigurationName) : 
    //            base(endpointConfigurationName) {
    //    }
        
    //    public RedPillClient(string endpointConfigurationName, string remoteAddress) : 
    //            base(endpointConfigurationName, remoteAddress) {
    //    }
        
    //    public RedPillClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
    //            base(endpointConfigurationName, remoteAddress) {
    //    }
        
    //    public RedPillClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
    //            base(binding, remoteAddress) {
    //    }
        
    //    public soapService.RedPillReference.ContactDetails WhoAreYou() {
    //        return base.Channel.WhoAreYou();
    //    }
        
    //    public long FibonacciNumber(long n) {
    //        return base.Channel.FibonacciNumber(n);
    //    }
        
    //    public soapService.RedPillReference.TriangleType WhatShapeIsThis(int a, int b, int c) {
    //        return base.Channel.WhatShapeIsThis(a, b, c);
    //    }
        
    //    public string ReverseWords(string s) {
    //        return base.Channel.ReverseWords(s);
    //    }
    //}
}
